version: '3.4'

services:
  db:
    container_name: test_instance
    image: mysql/mysql-server
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      # MYSQL_USER: db_admin
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql